// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	FindProductById(ctx context.Context, id int64) (Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	UpdateProductQuantity(ctx context.Context, arg UpdateProductQuantityParams) error
}

var _ Querier = (*Queries)(nil)
